# Replace evverything in Fastfile with below code
default_platform(:ios)
APPLICATON_ID = ENV["1632029735"]
BUNDLE_IDENTIFIER = ENV["com.duynp.testci"]
PROVISIONING_PROFILE_SPECIFIER = ENV["com.duynp.testci"]
TEMP_KEYCHAIN_USER = ENV["duynguyen"]
TEMP_KEYCHAIN_PASSWORD = ENV["123123"]
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: true,
    timeout: 360000
  )
end
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end
platform :ios do
  lane :beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      type: 'appstore',
      app_identifier: "#{BUNDLE_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(ENV["duynguyen242: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"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            APPLICATON_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )
    pilot(
      apple_id: "#{APPLICATON_ID}",
      app_identifier: "#{BUNDLE_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )
    delete_temp_keychain(keychain_name)
  end
end